### ISSUE TITLE
Implement selecting a revision

### ISSUE THREAD

**Issue by Belissimo-T** [ArtrenH/VPlan_FR#17]

**Comment by Belissimo-T** [comment]
can be implemented, now that 986ff4b is done

**Comment by Belissimo-T** [comment]
Lesson info links will be a problem. Currently we have no strategy for selecting an appropriate revision for a link.

**Comment by ArtrenH** [comment]
Now implemented in 81569dd5edd36c2f455bb495cf6d1bace8146e61
