### ISSUE TITLE
Missing authentication violates Datenschutz

### ISSUE THREAD

**Issue by Belissimo-T** [ArtrenH/VPlan_FR#2]

**Comment by ArtrenH** [comment]
Now implemented in the backend
login-forms still need support for csrf protection + frontend mostly missing

**Comment by OfficialFreak** [comment]
@ArtrenH Frontend is completed by now, I've seen you started to implemented CSRF Protection but disabled it for some tests. I'd say we enable it again, finish up the rest (if anything still needs to be done) and close this issue.

**Comment by ArtrenH** [comment]
csrf protection is now enabled in the backend and initislised for the app. All fetch requests are now done using the customFetch method and therefore send the necessary cookie.

**Comment by ArtrenH** [comment]
I am not sure, if every endpoint is protected though.
