### ISSUE TITLE
Allow schools, which are mlt 

### ISSUE THREAD

**Issue by SachsenspieltCoding** [ArtrenH/VPlan_FR#219]

**Comment by Belissimo-T** [comment]
I know you've closed this issue but I'm still interested in what "mlt" means in this context. Can you please explain?

**Comment by SachsenspieltCoding** [comment]
It means nothing because it was a typo. I accidentally opened this issue, so I closed it immediately.

(Yes, I know I could have edited it. The actual issue is #220)
