### ISSUE TITLE
Form button hidden in form plan, even though there can be multiple forms per lesson

### ISSUE THREAD

**Issue by Belissimo-T** [ArtrenH/VPlan_FR#25]

**Comment by OfficialFreak** [comment]
Rather than constantly displaying it, you could show it when multiple forms are present

**Comment by Belissimo-T** [comment]
@OfficialFreak You can do it that way. I wouldn't mind though if they were displayed all the time.

**Comment by OfficialFreak** [comment]
Fixed as Described in previous comment
