### ISSUE TITLE
Don't break table layout

### ISSUE THREAD

**Issue by Belissimo-T** [ArtrenH/VPlan_FR#36]
![image](https://github.com/ArtrenH/VPlan_FR/assets/37810842/6df3c0c8-5f65-40b6-a668-62209282c8ac)

In the third block, the columns are diffrent from the rest of the lessons. I'd suggest showing the forms
1. for all lessons, all the time
2. for all lessons if the day contains a single lesson with notable forms (for example multiple)
3. for all lessons, all the time but leave the forms table "cell" empty when the form is the currently selected one and this lesson only has this form, i. e. when the form is trivial.

**Comment by OfficialFreak** [comment]
fixed, added extra info in lesson-info
