### ISSUE TITLE
No support for teacher view

### ISSUE THREAD

**Issue by ArtrenH** [ArtrenH/VPlan_FR#48]
If someone had a teacher password, it would be useful to get access to actual teacher and room information

**Comment by Belissimo-T** [comment]
Do we always want to display the teacher room information or the extracted data from the form plan? Maybe offer both and provide a toggle switch?

**Comment by ArtrenH** [comment]
Isn't this finished with the fix of #81

**Comment by Belissimo-T** [comment]
@ArtrenH #81 was a duplicate of this issue. I closed it as "not planned".
This issue is fixed however because of commits 26578177 and cc15ee18.
