### ISSUE TITLE
2023-08-24 HAA

### ISSUE THREAD

**Issue by Belissimo-T** [ArtrenH/VPlan_FR#55]
2023-08-24 HAA

**Comment by ArtrenH** [comment]
classes weirdly grouped in block 4

**Comment by Belissimo-T** [comment]
This requires an additional grouping step since this a teacher plan. Currently, we only iterate once over the lessons. Teacher plans typically don't include annotations like "FACH Lehrer fällt aus" that is only relevant for form plans.

**Comment by ArtrenH** [comment]
I don't think we should get rid of that message since one of our goals is to display as much info as possible. The only thing that I think could be done better is to group them altogether and say something like "nur für 8/2: ... fällt aus"

**Comment by Belissimo-T** [comment]
fixed in 257c9d89
