### ISSUE TITLE
Scrape substitution plan from LernSax

### ISSUE THREAD

**Issue by Belissimo-T** [ArtrenH/VPlan_FR#57]

**Comment by ArtrenH** [comment]
Doesn't lernsax just scrape the plans from indiware?

**Comment by Belissimo-T** [comment]
@ArtrenH How would Lernsax scrape the subtitution plan if it is not available through indiware? Here are official instructions from Lernsax on how to connect Indiware:  https://www.lernsax.de/wws/bin/1464674-1465698-1-anleitung_vertretungsplan_v_indiware__2_.pdf
