### ISSUE TITLE
plan loader crashing often

### ISSUE THREAD

**Issue by ArtrenH** [ArtrenH/VPlan_FR#63]
- especially with proxies enabled, it just hangs itself after a few seconds
- additionally, some errors such as timouts are not handled

**Comment by Belissimo-T** [comment]
1. Currently, cannot reproduce. It takes a while for the proxies to warm up. Try adding `-l 9` to see all the log messages associated with proxies.
I think the [default request timeout](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L162) is 5 minutes which is probably too long.

2. Please provide a traceback.

**Comment by Belissimo-T** [comment]
To 1)
This just happened to me. I think that this has to do with the proxy selection mechanism which I wanted to rewrite either way.

**Comment by Belissimo-T** [comment]
To 2)
Could reproduce. This only happens when proxies are disabled. Otherwise the TimeoutError gets catched. I feel mixed about just ignoring this error when it occurs (when not using proxies).
