### ISSUE TITLE
Cluttered file and code structure

### ISSUE THREAD

**Issue by ArtrenH** [ArtrenH/VPlan_FR#78]
components that belong together should be put in special folders. See examples below. Additionally, some functions could be outsourced into other files.
File structure examples: (JUST A SUGGESTION, DON'T JUDGE ME)
- everything belonging to plans: (App), Plan, Lesson, Rooms, Weekplan
- things hiding under the navbar: Settings, Preferences, (SchoolManager), AboutUs
- essential parts: Navbar, Authorization

Especially functions that don't change variables but just stores could be outsourced. This is already done for the get_settings function but could also be done for the function that gets preferences.

**Comment by OfficialFreak** [comment]
I agree that refactoring and cleaning up the code is necessary. My suggestion for the file structure would be renaming the `Components` folder to `base_components` and creating a new `components` folder in which all remaining `.svelte` files are moved. That way, we have separated base- from high-level-components and other `.js` files such as the `utils`, `stores` etc.
