### ISSUE TITLE
Account database does not record account creation time

### ISSUE THREAD

**Issue by Belissimo-T** [ArtrenH/VPlan_FR#89]

**Comment by ArtrenH** [comment]
I think it does in the time_joined key. (As a unix timestamp)
Please provide more information or close the issue

**Comment by Belissimo-T** [comment]
@ArtrenH As far as I can tell, there is no `time_joined` key.

**Comment by ArtrenH** [comment]
![Screenshot_20230913_174036](https://github.com/ArtrenH/VPlan_FR/assets/79058115/92bafe19-672d-4243-a31d-91004f8ffdc0)
In my database view, it is there and it is also set in the signup function

**Comment by ArtrenH** [comment]
I just tested this with registering a new account and the field was set.
